// Code generated by Wire. DO NOT EDIT.

//go:generate go run github.com/google/wire/cmd/wire
//go:build !wireinject
// +build !wireinject

package wire

import (
	"fmt"
	"gorm.io/driver/postgres"
	"gorm.io/gorm"
	"log"
	"os"
	"todolist.firliilhami.com/internal/models"
	"todolist.firliilhami.com/internal/service"
)

// Injectors from wire.go:

func InitializeTaskServer() (*service.TaskServer, error) {
	string2 := newDatabaseURL()
	db, err := newDBConn(string2)
	if err != nil {
		return nil, err
	}
	taskServer := service.NewTaskServer(db)
	return taskServer, nil
}

// wire.go:

func newDatabaseURL() string {
	env := os.Getenv("env")
	var host string
	var port int32

	if env == "" {
		host = "localhost"
		port = 2222
	} else {
		host = "db"
		port = 5432
	}

	return fmt.Sprintf("host=%s port=%d user=postgres password=postgres dbname=postgres sslmode=disable", host, port)
}

func newDBConn(dsn string) (*gorm.DB, error) {

	db, err := gorm.Open(postgres.Open(dsn), &gorm.Config{})
	if err != nil {
		log.Fatalf("Failed to connect to the database: %v", err)
		return nil, err
	}

	err = db.AutoMigrate(&models.Task{})
	if err != nil {
		log.Fatalf("Failed to auto-migrate table: %v", err)
		return nil, err
	}

	return db, nil
}
